apiVersion: v1
kind: PersistentVolume
metadata:
  name: config-pv
  labels: 
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/config"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dns-dep
  labels:
    app: dns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dns
  template:
    metadata:
      labels:
        app: dns
    spec:
      containers:
        - name: dns
          image: coredns/coredns
          args: ["-conf", "/root/Corefile"]
          volumeMounts:
            - name: dns-config
              mountPath: "/root"
          ports:
            - containerPort: 100
              protocol: UDP
      volumes:
        - name: dns-config
          persistentVolumeClaim:
            claimName: config-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: dns-svc
spec:
  selector:
    app: dns
  ports:
    - protocol: UDP
      port: 31000
      nodePort: 31000
      targetPort: 100
  type: NodePort
