apiVersion: v1
kind: PersistentVolume
metadata:
  name: config-pv
  labels: 
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/config"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dns-dep
  labels:
    app: dns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dns
  template:
    metadata:
      labels:
        app: dns
    spec:
      containers:
        - name: dns
          image: coredns/coredns
          args: ["-conf", "/root/Corefile"]
          volumeMounts:
            - name: dns-config
              mountPath: "/root"
          ports:
            - containerPort: 100
              protocol: UDP
      volumes:
        - name: dns-config
          persistentVolumeClaim:
            claimName: config-pvc
    #  volumes:
    #    - name: dns-config
    #      configMap:
    #         name: dns-config
---
#apiVersion: v1
#kind: ConfigMap
#metaData:
#  name: dns-config
#data:
#  Corefile: | -
#    .:100 {
#      forward . 8.8.8.8 9.9.9.9
#      log
#      errors
#    }
#    
#    example.com:100 {
#      file /root/example.db
#      log
#      errors
#    }
#  example.db: | -
#    example.com.        IN  SOA dns.example.com. robbmanes.example.com. 2015082541 7200 3600 1209600 3600
#    gateway.example.com.    IN  A   192.168.1.1
#    dns.example.com.    IN  A   192.168.1.2
#    host.example.com.   IN  A   192.168.1.3
#    server.example.com. IN  CNAME   host.example.com
#---
apiVersion: v1
kind: Service
metadata:
  name: dns-svc
spec:
  selector:
    app: dns
  ports:
    - protocol: UDP
      port: 31000
      targetPort: 100
  type: NodePort
